# Generated by Django 5.1.7 on 2025-03-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='seating_chart',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='booking',
            name='seats',
            field=models.JSONField(default=list),
        ),
    ]
